Home work 2
IlyaRF/HomeWork pull request #13
Opened 2022-05-30 20:56 UTC by IlyaRF

ДЗ№2

2022-06-01 15:31 UTC, efserg requested changes

2022-06-01 15:31 UTC, efserg commented on src/main/java/ru/GB/Gaitanov/I/secondquarter/HomeWork2/main.java
> +    public static void MyArrayDataExeption(int[][] numbers) {
Нет, надо не создавать метод, а создать исключение, и "бросить" его при необходимости

2022-06-01 19:02 UTC, merged

2022-06-06 16:12 UTC, efserg reviewed
Исправляйте видимость полей

2022-06-06 16:12 UTC, efserg commented on src/main/java/ru/GB/Gaitanov/I/secondquarter/HomeWork2/Main.java
> +        public int j;
С публичными полями не принимаю дз

2022-10-11 08:41 UTC, IlyaRF commented
Добрый вечер, Сергей. Внес изменения в  видимость полей.

пн, 6 июн. 2022 г. в 19:12, Sergey Efremov ***@***.***>:

> ***@***.**** commented on this pull request.
>
> Исправляйте видимость полей
> ------------------------------
>
> In src/main/java/ru/GB/Gaitanov/I/secondquarter/HomeWork2/Main.java
> <https://github.com/IlyaRF/HomeWork/pull/13#discussion_r890311063>:
>
> > +        public int i;
>
> +        public int j;
>
>
> С публичными полями не принимаю дз
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/IlyaRF/HomeWork/pull/13#pullrequestreview-996849574>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AYVI5LPU7LB3ARZQSHLTKTDVNYPORANCNFSM5XLR25XA>
> .
> You are receiving this because you modified the open/close state.Message
> ID: ***@***.***>
>